name = "nova-v2"
compatibility_date = "2024-09-01"
compatibility_flags = [ "nodejs_compat" ]
main = "public/_worker.js"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
RESEND_FROM_EMAIL = "Nova Assessments <evaluations@openhire.in>"
RESEND_REPLY_TO_EMAIL = "support@openhire.in"
VITE_GOOGLE_DRIVE_FOLDER_ID = "1WkOdrNQYq8IrxAxMykjyHGmsko9T81q3"
